### ISSUE TITLE
`@event` macro not working?

### ISSUE THREAD

**Issue by svilupp** [GenieFramework/Stipple.jl#315]
I suspect that the `@event` macro is not working in the latest Stipple (v0.31).

I noticed it when trying to resolve uploading/downloading of files and getting errors about the model not being initialized. I've filed the full issue here with an MWE: https://github.com/GenieFramework/StippleDownloads.jl/issues/3

However, it seems to be mainly a Stipple problem, which can be tested easily by including any `@event` in the `@app` block. It won't even start.

Even if you manage to get around the late model type creation and the event seems to be registered (no warnings show up when it's triggered), the actual code registered with the event never runs (again see the above issue for MWE).

Versions:
  [c43c736e] Genie v5.33.0
  [4acbeb90] Stipple v0.31.3
  [291a174b] StippleDownloads v0.1.4

Running on Julia 1.11.3

**Comment by hhaensel** [comment]
Could you please try moving the event out of the app block?

**Comment by svilupp** [comment]
Thank you for responding! 

Yes, I have tried that -- it's documented in the original issue on StippleDownloads (that's how I first noticed it): https://github.com/GenieFramework/StippleDownloads.jl/issues/3

When the event is defined after, you avoid the type-not-defined error, but it seems that the event itself is not registered. If I trigger it, I see "error ABC not defined".

Do you have any tips how to investigate further? 
- Where do I look if the event is registered? 
- Is there a way to register the event without macros?

**Comment by hhaensel** [comment]
Should have been fixed with Stipple v0.31.2

**Comment by svilupp** [comment]
Thank you for responding. The above code was run on 0.31.3 and still failing.

I just checked your **latest released 0.31.5 and the issue persists**, although there is an improvement (event code block is executed on the server).

1) `@event` must be defined outside of `@app` block (to prevent the type not defined error)

2) I must use the return type of `@app` instead of just explicit model name, eg, `@app MyModel begin...end` and `@event MyModel :my_event begin...end` does not throw any errors, but upon event trigger it says "event my_event not defined".

3) The server-side code block is now executed (I can see the logs), however, the download never shows up on the client. I've tested with and without client filtering and with `download_text` and `download_binary` to sense check. I've restarted my REPL three times to confirm.

MWE:
```
module Download
using Stipple, Stipple.ReactiveTools
using StippleUI, StippleDownloads

T = @app begin
    @in data = randn(1000)
    @in text = "Hello, world!"
    @in download_raw = false
end

@event T :download_raw begin
    @info "Downloading raw data"
    # download_text(__model__, :text)
    download_binary(__model__, data, "raw.txt"; client = event["_client"])
    @info "Download complete"
end
function ui()
    row([cell(btn(class = "q-ml-lg", "Raw", icon = "download",
        @on(:click, :download_raw, :addclient), color = "primary", nocaps = true))
    ])
end

@page("/", ui)
Stipple.up()
end # end of module
```

**Comment by svilupp** [comment]
Amazing, thank you! I can confirm that the MWE works.

I'm still having issues getting it to work with my actual app, so I'll leave this open for a few more days to see if I can fix it!

Have a great weekend!

**Comment by svilupp** [comment]
All works well -- thank you so much!

Tested on Stipple 0.31.7 and Genie 5.33!

**Comment by svilupp** [comment]
FYI. this package combination breaks in PROD because of some MIME type errors, I'll open a separate issue once I isolate it
